<a href="https://colab.research.google.com/github/JasmineVan/NumpyFundamental/blob/main/51800128_TrinhVanThuong_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Giới thiệu thư viện Numpy

NumPy là một thư viện Python được sử dụng để làm việc với các mảng.
Nó cũng có các chức năng để làm việc trong miền đại số tuyến tính.

NumPy được tạo ra vào năm 2005 bởi Travis Oliphant. Nó là một thư viện mã nguồn mở và có thể sử dụng nó một cách tự do.

NumPy là viết tắt của Numerical Python.

NumPy nhằm mục đích cung cấp một đối tượng mảng nhanh hơn tới 50 lần so với Python truyền thống.

Đối tượng mảng trong NumPy được gọi là ndarray, nó cung cấp rất nhiều hàm hỗ trợ giúp cho việc làm việc với ndarray trở nên rất dễ dàng.

Mảng được sử dụng rất thường xuyên trong khoa học dữ liệu, nơi mà tốc độ và tài nguyên là rất quan trọng.

#Thư viện Numpy

##Cài đặt và sử dụng numpy:

In [ ]:
#pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

1.21.5


##Khởi tạo:

In [ ]:
#ndarray
arr = np.array([1, 2, 3, 4, 5])
print("Create n-d array\n", arr)

Create n-d array
 [1 2 3 4 5]


In [ ]:
#1-d array
arr = np.array([1, 2, 3, 4, 5])
print("Create 1-d array\n", arr)

Create 1-d array
 [1 2 3 4 5]


In [ ]:
#2-d array
arr = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print("Create 2-d array\n", arr)

Create 2-d array
 [[1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
#3-d array
arr = np.array([[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]], [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]])
print("Create 3-d array\n", arr)

Create 3-d array
 [[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]


In [ ]:
#Xem số chiều của mảng
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
c = np.array([[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]], [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [ ]:
#Tạo mảng với số chiều mong muốn
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('Number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions: 5


In [ ]:
#Tạo mảng 0 với số phần tử mong muốn
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Tạo mảng 1 với số phần tử mong muốn
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#Hàm arange(n) tạo mảng 1 chiều từ 0 đến n
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#Tạo mảng 1 chiều với các phần tử có giá trị nguyên ngẫu nhiên từ 0 - 10, số lượng phần tử size
arr = np.random.randint(low = 0, high = 10, size = 10)
print(arr)

[6 5 2 9 5 7 4 9 1 6]


In [ ]:
#Tạo mảng 2 chiều với các phần tử có giá trị nguyên ngẫu nhiên, mỗi mảng gồm 3 mảng con có 10 phần tử
arr = np.random.randint(10, size =(3, 10))
print(arr)

[[1 8 9 5 9 0 0 7 7 0]
 [9 7 1 3 0 3 6 6 1 0]
 [4 3 3 8 0 2 8 9 9 6]]


In [ ]:
#Tạo mảng 3 chiều với các phần tử có giá trị nguyên ngẫu nhiên từ 0 - 10, mỗi mảng gồm 2 mảng 2 chiều mỗi mảng gồm 2 mảng con 10 phần tử
arr = np.random.randint(0, 10, (2, 2, 10))
print(arr)


[[[4 8 1 2 8 7 5 9 9 5]
  [6 0 0 8 6 5 4 2 3 6]]

 [[1 5 3 0 6 6 4 1 7 8]
  [2 6 3 0 1 1 3 4 2 7]]]


In [ ]:
#Tạo mảng 1 chiều với các phần tử có giá trị thực ngẫu nhiên, số lượng phần tử size
arr = np.random.ranf(size=10)
print(arr)

[0.24213134 0.92045956 0.31335022 0.2913246  0.89096227 0.58721532
 0.45635957 0.88767961 0.64084876 0.57637046]


In [ ]:
#Tạo mảng 2 chiều với các phần tử có giá trị thực ngẫu nhiên gồm 2 mảng con mỗi mảng 3 phần tử
arr = np.random.ranf(size =(2, 3))
print(arr)

[[0.58682076 0.51323473 0.82487412]
 [0.48370505 0.59336785 0.01376343]]


In [ ]:
#Tạo mảng 3 chiều với các phần tử có giá trị thực ngẫu nhiên gồm 2 mảng 2 chiều gồm 3 con mỗi mảng 3 phần tử
arr = np.random.ranf((2, 3, 3))
print(arr)

[[[0.88308781 0.51478029 0.45871248]
  [0.50700233 0.4591955  0.92150857]
  [0.60121007 0.59794937 0.71897937]]

 [[0.0182993  0.47515067 0.85821244]
  [0.17019955 0.3117756  0.03094028]
  [0.12489289 0.04359944 0.70170116]]]


##Tham chiếu đến phần tử trong n-darray

In [ ]:
#1-d array
arr = np.array([1, 2, 3, 4, 5])
print(arr[1])
print(arr[:4])

2
[1 2 3 4]


In [ ]:
#2-d array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('1st element on 1st row: ', arr[0, 0])
print('5th element on 2nd row: ', arr[1, 4])

1st element on 1st row:  1
5th element on 2nd row:  10


In [ ]:
#3-d array
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10]], [[11,12,13,14,15], [16,17,18,19,20]]])

print("the element which value is 1:", arr[0, 0, 0])
print("the element which value is 11:", arr[1, 0, 0])

the element which value is 1: 1
the element which value is 11: 11


In [ ]:
#Lấy phần tử cuối cùng trong mỗi n-darray
arr1 = np.array([1,2,3,4,5])
print('Last element: ', arr1[-1])
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr2[1, -1])
arr3 = np.array([[[1,2,3,4,5], [6,7,8,9,10]], [[11,12,13,14,15], [16,17,18,19,20]]])
print('Last element from 2nd dim 2nd row: ', arr3[1, 1, -1])

Last element:  5
Last element from 2nd dim:  10
Last element from 2nd dim 2nd row:  20


##Cắt mảng (Slice)



###1-d array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#Từ index 1 đến index 5 (không bao gồm phần tử index 6)
print(arr[1:5])
#Từ index 4 đến hết (bao gồm cả phần tử index 4)
print(arr[4:])
#Từ đầu đến index 4 (không bao gồm cả phần tử index 4)
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#Cắt mảng có sử dụng thêm bước nhảy(step)
print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5 7]


###2-d array

In [ ]:
#Cắt lấy phần tử index 2 ở cả 2 phần của mảng 2-darray
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [ ]:
#Cắt lấy phần tử từ index 1 đến index 4 (không bao gồm phẩn tử index 4) ở cả 2 phần của mảng 2-darray
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


##Kiểu dữ liệu của mảng (Data type)

1. i - integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. m - timedelta
7. M - datetime
8. O - object
9. S - string
10. U - unicode string
11. V - fixed chunk of memory for other type ( void )

In [ ]:
#Xem kiểu dữ liệu của mảng
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = np.array(["dog", "cat", "duck", "bird"])
print(arr.dtype)

int64
<U4


In [ ]:
#Tạo mảng với kiểu dữ liệu mong muốn
arr = np.array([1, 2, 3, 4], dtype='<U4')
print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U4
[1 2 3 4]
int32


In [ ]:
#Chuyển mảng float thành mảng int
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
#Chuyển mảng int thành mảng boolean
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


##Hình dạng của mảng (Shape)


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr.shape)

(2, 5)


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


##Chuyển dạng mảng (Reshape)

In [ ]:
#Chuyển mảng 1 chiều thành mảng 2 chiều chứa 4 mảng, mỗi mảng 3 phần tử
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Chuyển mảng 1 chiều thành mảng 3 chiều chứa 2 mảng, mỗi mảng gồm 3 mảng với 2 phần tử
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


##Duyệt qua các phần tử trong mảng (Iterating)

In [ ]:
#1-darray
arr = np.array([1, 2, 3, 4, 5])
for x in arr:
  print(x)

1
2
3
4
5


In [ ]:
#2-darray
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)
  for y in x:
    print(y)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [ ]:
#3-darray
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)
  for y in x:
    print(y)
    for z in y:
      print(z)

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
2
3
[4 5 6]
4
5
6
[[ 7  8  9]
 [10 11 12]]
[7 8 9]
7
8
9
[10 11 12]
10
11
12


In [ ]:
#Đối với các mảng có nhiều chiều (dimension lớn) thì việc viết các vòng lặp for sẽ gây khó khăn nên thay vào đó sử dụng nditer()
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#Enumarate vừa duyệt vừa trả về vị trí của phần tử vừa duyệt qua
arr = np.array([1, 2, 3])
print("1-d array")
for idx, x in np.ndenumerate(arr):
  print(idx, x)

print("2-d array")
arr = np.array([[1, 2, 3], [4, 5, 6]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

print("3-d array")
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

1-d array
(0,) 1
(1,) 2
(2,) 3
2-d array
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
3-d array
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


##Ghép mảng (Concatenate)

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
#Ghép 2 mảng arr1 và arr2 thành mảng arr gồm 4 mảng mỗi mảng 2 phần tử
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)
#Ghép 2 mảng arr1 và arr2 thành mảng arr gồm 2 mảng mỗi mảng 4 phần tử
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Hàm stack() xếp chồng theo index của mỗi mảng
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Hàm hstack() xếp chồng theo hàng
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
#Hàm vstack() xếp chồng theo cột
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Hàm dstack() xếp chồng theo chiều cao/chiều sâu
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


##Chia mảng (Split)

###1-d array

In [ ]:
#Chia mảng thành 3 phần (mảng được chia có số phần tử đủ để chia thành các mảng con với số lượng như nhau)
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#Chia mảng thành 4 phần (mảng được chia có số phần tử không đủ để chia, array_split() sẽ tự điều chỉnh số lượng phần tử, trường hợp này dùng split sẽ lỗi)
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
#Giá trị trả về của split hay array_split sẽ là n mảng con
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


###2-d array

In [ ]:
#Chia mảng 2-d thành 3 mảng con
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [ ]:
#Chia mảng theo hàng
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)

print(newarr[0])
print(newarr[1])
print(newarr[2])
#Tương tự có hàm hsplit()
newarr2 = np.hsplit(arr, 3)
# print(newarr2[0])
# print(newarr2[1])
# print(newarr2[2])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [ ]:
#Chia mảng theo cột
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=0)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


##Tìm kiếm trong mảng (Search)

In [ ]:
#Trả về vị trí của phần tử có giá trị cần tìm
arr = np.array([1, 2, 3, 4, 5])

x = np.where(arr == 5)
print(x)

(array([4]),)


In [ ]:
#Trả về index của phần tử chẵn trong mảng
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [ ]:
#Trả về index của phần tử lẻ trong mảng
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6]),)


In [ ]:
#Sắp xếp lại mảng sau đó chèn giá trị truyền vào của hàm, duyệt từ trái sang
arr = np.array([6, 5, 6, 7, 5, 4])
x = np.searchsorted(arr, 8)
print(x)

6


In [ ]:
#Sắp xếp lại mảng sau đó chèn giá trị truyền vào của hàm, duyệt từ phải sang
arr = np.array([6, 7, 8, 8, 9])
x = np.searchsorted(arr, 8, side='right')
print(x)

4


##Sắp xếp mảng (Sort)

###1-d array

In [ ]:
#Hàm sort() sắp xếp lại mảng int theo giá trị từ bé đến lớn 
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
#Hàm sort() sắp xếp lại mảng string theo alphabelt 
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
#Hàm sort() sắp xếp lại mảng bolean false trước, true sau
arr = np.array([True, False, True, False])
print(np.sort(arr))

[False False  True  True]


###2-d array

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
arr = np.array([['banana', 'cherry', 'apple'], ['mango', 'pear', 'coconut']])
print(np.sort(arr))

[['apple' 'banana' 'cherry']
 ['coconut' 'mango' 'pear']]


###3-d array

In [ ]:
arr = np.array([[[8, 1, 4], [2, 2, 1]], [[3, 9, 4], [1, 2, 1]]])
print(np.sort(arr))

[[[1 4 8]
  [1 2 2]]

 [[3 4 9]
  [1 1 2]]]


In [ ]:
arr = np.array([[['banana', 'cherry', 'apple'], ['mango', 'pear', 'coconut']], [['banana', 'cherry', 'apple'], ['mango', 'pear', 'coconut']]])
print(np.sort(arr))

[[['apple' 'banana' 'cherry']
  ['coconut' 'mango' 'pear']]

 [['apple' 'banana' 'cherry']
  ['coconut' 'mango' 'pear']]]


##Lọc dữ liệu trong mảng (Filter)

In [ ]:
#Phần tử trong mảng có index là True thì phần tử đó được liệt vào mảng đã lọc
arr = np.array([1, 2, 3, 4, 5])
x = [True, False, True, False, True]
newarr = arr[x]
print(newarr)

[1 3 5]


In [ ]:
#Ví dụ lấy những phần tử chẵn trong mảng
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
filter_arr = []
for element in arr:
  if element %2 ==0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(newarr)

[ 2  4  6  8 10 12]


In [ ]:
#Lấy những phần tử chẵn trong mảng (Cách 2)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
filter_arr = arr %2 == 0
newarr = arr[filter_arr]
print(newarr)

[ 2  4  6  8 10 12]


##Xử lí chuỗi (String operations)



In [ ]:
#Hàm lower in thường tất cả phần tử trong mảng
print(np.char.lower(['BANANA', 'APPLE', 'COCONUT']))

['banana' 'apple' 'coconut']


In [ ]:
#Hàm inumeric trả về True nếu phần tử là số
print(np.char.isnumeric(['Apple', 1]))

[False  True]


In [ ]:
#Hàm isalpha trả về True nếu phần tử là chữ
print(np.char.isalpha(['Apple', 1]))

[ True False]


In [ ]:
#Hàm isupper trả về True nếu phần tử in hoa
print(np.char.isupper(['APPLE', 'banana']))

[ True False]


##Đếm trong mảng (Count)


In [ ]:
#Hàm count_nonzero trả về số lượng phần tử trong mảng khác 0
a = np.count_nonzero([[0,1,7,0,0],[3,0,0,2,19]])
print(a)

5


In [ ]:
#Hàm argmax() trả về index của giá trị lớn nhất trong mảng
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
np.argmax(a)

[1 2 3 4 5 6 7 8 9]


8

In [ ]:
#Hàm argmin() trả về index của giá trị lớn nhất trong mảng
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
np.argmin(a)

[1 2 3 4 5 6 7 8 9]


0

In [ ]:
#hàm amin() trả về phần tử nhỏ nhất trong mảng
a = [11, 22, 33, 44, 55, 66, 77, 88, 99, 111]
print(np.amin(a))

11


In [ ]:
#hàm amax() trả về phần tử lớn nhất trong mảng
a = [11, 22, 33, 44, 55, 66, 77, 88, 99, 111]
print(np.amax(a))

111


In [ ]:
#Hàm ptp() trả về hiệu số giữa phần tử lớn nhất và phần tử nhỏ nhất trong mảng
a = [11, 22, 33, 44, 55, 66, 77, 88, 99, 111]
print(np.ptp(a))

100


In [ ]:
#Hàm mean() trả về giá trị trung bình của mảng
a = [11, 22, 33, 44, 55, 66, 77, 88, 99, 111]
print(np.mean(a))

60.6


In [ ]:
#Hàm median() trả về trung vị của mảng
a = [11, 22, 33, 44, 55, 66, 77, 88, 99, 111]
print(np.median(a))

60.5


#Tài liệu tham khảo

https://numpy.org/doc/stable/numpy-user.pdf

https://www.geeksforgeeks.org/python-numpy/

https://www.w3schools.com/python/numpy/default.asp